### ISSUE TITLE
Can't install/build

### ISSUE THREAD

**Issue by ghost** [bjarneo/rip#10]
build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element

**Comment by bjarneo** [comment]
Hi, @xor5 
I am not having this issue. What OS are you trying to do this from?

What Go version?

**Comment by ghost** [comment]
Fixed it by updating to a newer go version.

**Comment by bjarneo** [comment]
That is awesome, @xor5 

So to others: to use embed you need version >= 1.16
