### ISSUE TITLE
Will you still update it?

### ISSUE THREAD

**Issue by kitcoun** [bjarneo/rip#3]
It looks good, but the function is too simple

**Comment by bjarneo** [comment]
Yes, this is a pet project of mine I am going to continuously work on.

What do you feel is missing as you mention it is too simple? I have more ideas myself, but I would like feedback on this part.

**Comment by kitcoun** [comment]
Proxy and more request headers

Maybe you can learn from other people's open source code ideas

**Comment by bjarneo** [comment]
> Proxy and more request headers
> 
> Maybe you can learn from other people's open source code ideas

Sounds good. 👌
